---
title: "RWorksheet_Calvario#1"
author: "Jolien"
date: "2024-09-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.
```{r}
age<-c(34, 28, 22, 36, 27,18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51, 35, 24, 33, 41)
```


```{r}
length(age)
```
# 34 data points

2. 
```{r}
reciprocal <- 1/age
print(reciprocal)
```
3.
```{r}
new_age <- c(age, 0, age)
print(new_age)
```
4.
```{r}
sort (age)
```
5.

```{r}
min (age)
max (age)
```
# 17 is the minimum
# 57 is the maximum

6.
```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)
```

```{r}
length(data)
```
# 12 data points

7.
# the vector results in a new vector where each element is twice the original element.
```{r}
new_vector <-(data)
data * 2
```
8.1
```{r}
f <- seq(1:100)
```

8.2
```{r}
g <- seq(20:60)
```

8.3
```{r}
h <- mean(20,60)
```

8.4
```{r}
i <- sum(51,91)
```

8.5
```{r}
j <- seq(1:1000)
```

a.
```{r}
length1 <- length(f)
length2 <- length(g)
length3 <- length(h)
length4 <- length(i)
sum(length1+length2+length3+length4)
```
# 143 data points from 8.1 to 8.4

b.
```{r}
f <- seq(1:100)
g <- seq(20:60)
h <- mean(20,60)
h <- mean(20,60)
```

c.
```{r}
max
```

"9. Print a vector with the integers between 1 and 100 that are not divisible by 3,5, and 7 using filter option."

"Filter(function(i) {all(i %% c(3,7,5) != 0)} seq(100))"
```



